name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    - name: Grant gradlew permission
      run: chmod +x gradlew

    - name: Run unit tests
      run: ./gradlew test

    - name: Start ADB
      run: |
        adb start-server
        adb devices

    - name: Run instrumentation tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        profile: Nexus 6
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -no-snapshot
        disable-animations: true
        emulator-boot-timeout: 900
        script: |
          adb wait-for-device
          adb shell input keyevent 82
          ./gradlew connectedDebugAndroidTest
